### PR TITLE
[mod] better, more helpful, more detailed, more didactic

### PR DESCRIPTION
**Pull request by sassbalint**
Improved based on my experience in creating a concrete, authentic `xtsv` module.
Review and merge, please.

### CODE REVIEW

**Comment by dlazesz** [comment]
Thanks for your contribution! Generally, the modifications are looking nice. See details below.

### Some minor modifications and questions:

- [HERE](https://github.com/nytud/emdummy/pull/4/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R100) `time` command was used to make basic benchmark on execution time and can be used for comparison between commits later.
I'd like to see it readded.

- IMO It also would be helpful  if the test command was to be echoed for manual running or debugging purposes if anything fails.

- I would keep [THIS](https://github.com/nytud/emdummy/pull/4/files#diff-06a10e6e6e20c4914c96aaf573a7a54ad70f983e51cd36e737801a7d365749a1L28) line, as it is required in config.py

- Here I miss the step of adding the import to config.py:
https://github.com/nytud/emdummy/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56

- typo:
    emdummy/emdummy.py:
    > to be able to convert in noth directions.
    
    BOTH directions.

### Other notes

This might be at better place in README.md: https://github.com/nytud/emdummy/blob/master/docs/CONTRIBUTING.md#seting-up-ci-with-travis-ci

If this PR settles #1 I will close upon merge.

**Comment by sassbalint** [comment]
> Thanks for your contribution! Generally, the modifications are looking nice. See details below.

:+1:

> [HERE](https://github.com/nytud/emdummy/pull/4/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R100) `time` command was used to make basic benchmark on execution time and can be used for comparison between commits later. I'd like to see it readded.
>
> IMO It also would be helpful  if the test command was to be echoed for manual running or debugging purposes if anything fails.

:heavy_check_mark: 

> I would keep [THIS](https://github.com/nytud/emdummy/pull/4/files#diff-06a10e6e6e20c4914c96aaf573a7a54ad70f983e51cd36e737801a7d365749a1L28) line, as it is required in config.py
> 
> Here I miss the step of adding the import to config.py: [#4 (files)](https://github.com/nytud/emdummy/pull/4/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56)

I do not see such an `import` in the [`emtsv` config file.](https://github.com/nytud/emtsv/blob/master/config.py) Please help, what I am missing.

 > typo: emdummy/emdummy.py: "noth" -> "both"

:heavy_check_mark: 

> This might be at better place in README.md: [`master`/docs/CONTRIBUTING.md#seting-up-ci-with-travis-ci](https://github.com/nytud/emdummy/blob/master/docs/CONTRIBUTING.md?rgh-link-date=2021-12-03T20%3A31%3A07Z#seting-up-ci-with-travis-ci)

Should I simply transfer this part of `CONTRIBUTING.md` to `README.md`?

> If this PR settles #1 I will close upon merge.

I don't really get this point. :) __update:__ OK, I see, if I solved #1 with this PR, you will close #1. I'm afraid, I won't solve it right now.

**Comment by dlazesz** [comment]
> I do not see such an import in the emtsv config file. Please help, what I am missing.

Sorry. You are right. The old behaviour was the import stuff. :D
There is nothing to do with this.

> Should I simply transfer this part of CONTRIBUTING.md to README.md?
 
At least it should be referenced. Because this is a dummy module CONTRIBUTING.md is closer in content to README.md than for a normal module.

In other words: Is the content of CONTRIBUTING.md good or you can see some room for improvement, witch might be included in this PR?
 
 > I'm afraid, I won't solve it right now.
 
:( If you have any idea, you are welcome to include it in this PR.

**Comment by dlazesz** [comment]
Merged to harmonise it with #3

**Pull request merged**
